#!/bin/bash

# Check that inotifywait is installed.
which inotifywait 1>/dev/null
if [ $? -ne 0 ]; then
    echo This script uses 'inotifywait' to watch for local filesystem changes.
    echo Please install it with: \'sudo apt install inotify-tools\'
    exit 1
fi

# Build the project and start the server as a background process.
host=0.0.0.0
port=5000
python3.9 run.py --context-file=context.json --development --serve \
    --host=$host --port=$port &
# Get the background process's PID.
server_pid=$!

# Register a CTRL-C interrupt handler.
trap ctrl_c INT

# On CTRL-C, terminate the background server process and exit.
function ctrl_c() {
    kill -SIGKILL $server_pid
    exit 0
}

# Rebuild on any changes outside of the site/ dir.
while true; do
    inotifywait -e modify --recursive --quiet --quiet --exclude site/ *;
    python3.9 run.py --context-file=context.json --development;
    curl --silent -XPOST http://$host:$port/_reload
done
