"""Microdata constants.
"""

CONTACT_POINT = 'https://schema.org/ContactPoint'
CREATIVE_WORK = 'https://schema.org/CreativeWork'
IMAGE_OBJECT = 'https://schema.org/ImageObject'
INTANGIBLE = 'https://schema.org/Intangible'
ITEM_LIST = 'https://schema.org/ItemList'
LIST_ITEM = 'https://schema.org/ListItem'
MEDIA_OBJECT = 'https://schema.org/MediaObject'
PERSON = 'https://schema.org/Person'
SOFTWARE_SOURCE_CODE = 'https://schema.org/SoftwareSourceCode'
VIDEO_OBJECT = 'https://schema.org/VideoObject'

ABSTRACT = 'abstract'
ASSOCIATED_MEDIA = 'associatedMedia'
CODE_RESPOSITORY = 'codeRepository'
CONTACT_POINT_PROP = 'contactPoint'
CONTENT_URL = 'contentUrl'
DESCRIPTION = 'description'
EMAIL = 'email'
ENCODING_FORMAT = 'encodingFormat'
HAS_PART = 'hasPart'
IMAGE = 'image'
IS_PART_OF = 'isPartOf'
ITEM_LIST_ELEMENT = 'itemListElement'
NAME = 'name'
POSITION = 'position'
SAME_AS = 'sameAs'
SUBJECT_OF = 'subjectOf'
THUMBNAIL_URL = 'thumbnailUrl'
UPLOAD_DATE = 'uploadDate'
URL = 'url'
